In [1]:
import pandas as pd

In [2]:
# Tabela 1.1

df1 = pd.read_csv('../datasets/tabela1_1.csv')
df1.columns = ['ID', 'BAIRO', 'TIPO', 'Nº de Quartos', 'Preço']
df1

    ID        BAIRO   TIPO Nº de Quartos  Preço
0    1        Barra  Apto.             2    165
1    2        Barra  Apto.             3    240
2    3        Barra  Cobt.           NaN    158
3    4        Barra   Sala           NaN    150
4    5     Botafogo  Apto.             2     59
5    6       Catete  Apto.             1     54
6    7       Centro   Sala           NaN     35
7    8   Copacabana  Apto.             2     83
8    9   Copacabana  Apto.             3    180
9   10   Copacabana  Apto.            4+     85
10  11     Flamengo  Apto.             1     58
11  12     Flamengo  Cobt.           NaN    120
12  13        Gávea  Apto.            4+    250
13  14      Ipanema  Apto.             3    130
14  15  Jacarepaguá  Apto.             3     90
15  16        Lagoa  Apto.             2    130
16  17  Laranjeiras  Apto.             2     68
17  18  Laranjeiras  Apto.            4+    360
18  19       Leblon  Apto.             3    300
19  20       Leblon  Apto.            4+    600
20  21     Maracanã  Apto.             3    137
21  22      Recreio  Cobt.           NaN    240
22  23  São Conrado   Casa            4+    650
23  24       Tijuca  Apto.             2     49
24  25       Tijuca  Apto.             2     95
25  26       Tijuca  Apto.            4+    170
26  27  Vila Isabel  Apto.             2     57

In [3]:
print('Variveis Qualitativas Nominal: %s e %s' % ('BAIRRO', 'TIPO'))

Variveis Qualitativas Nominal: BAIRRO e TIPO

In [4]:
print('Varivel Qualitativa Ordinal: %s' % '"Nº de Quartos"')

Varivel Qualitativa Ordinal: "Nº de Quartos"

In [5]:
print('Variavel Quantitativa Continua: %s' % 'Preço')

Variavel Quantitativa Continua: Preço

In [29]:
import numpy as np
import decimal
#import Conversao as Conv
import Funcoes.Conversao as Conv

In [30]:
#   1.4.1 Tabelas de Frequencia para Variaveis Qualitativas

#   Cada linha corresponde a um valor possível da variável
#   Usando contagem os valores que constam na coluna de frequência (Frequência Absoluta) são encontrados
#   Com os valores da Frequência Absoluta, calcula-se a Frequência Relativa, sobre a forma de percentuais.

In [31]:
freq1 = Conv.frequencia_relativa([5, 20, 20])

11.11	44.45	44.44	100.00

In [32]:
freq2 = Conv.frequencia_relativa([16, 16, 12, 1])

35.55	35.56	26.67	2.22	100.00

In [33]:
freq3 = Conv.frequencia_relativa([1,9,5,8,1,1,1,0,1])

3.70	33.35	18.52	29.63	3.70	3.70	3.70	0.00	3.70	100.00

In [1]:
import numpy as np
import pandas as pd
# Tabela 1.2

df2 = pd.read_csv('../datasets/tabela1_2.csv')
#df1.columns = ['ID', 'BAIRO', 'TIPO', 'Nº de Quartos', 'Preço']
df2

,id,categ,idade,peso,altura,imc,classe_imc,cintura,quadril,rcq,classe_rcq
0,ID1,A,61,58.2,154.0,24.5,normal,87,109,0.80,MR
1,ID2,S,69,63.0,152.0,27.3,sobrepeso,89,104,0.86,GR
2,ID3,S,61,70.1,158.0,28.1,sobrepeso,106,123,0.86,GR
3,ID4,S,71,73.2,156.0,30.1,sobrepeso,110,122,0.90,GR
4,ID5,A,63,58.6,152.0,25.4,sobrepeso,99,121,0.82,MR
5,ID6,S,71,77.0,160.0,30.1,sobrepeso,125,132,0.95,GR
6,ID7,S,72,76.2,165.0,28.0,sobrepeso,115,125,0.92,GR
7,ID8,S,68,59.8,160.0,23.4,normal,85,103,0.83,MR
8,ID9,A,66,64.3,155.0,26.8,sobrepeso,100,120,0.83,MR
9,ID10,S,69,52.1,151.0,22.8,normal,74,83,0.89,GR
10,ID11,S,72,62.0,156.0,22.5,sobrepeso,90,111,0.81,MR
11,ID12,S,67,52.1,151.0,22.8,normal,76,90,0.84,MR
12,ID13,S,63,58.0,157.0,23.5,normal,80,102,0.78,MR
13,ID14,S,66,55.0,154.0,23.2,normal,78,96,0.81,MR
14,ID15,S,63,50.1,157.0,20.3,normal,72,81,0.89,GR
15,ID16,A,63,57.9,160.0,22.6,normal,78,90,0.87,GR
16,ID17,A,60,58.2,156.0,23.9,normal,80,108,0.74,PR
17,ID18,A,67,56.2,152.0,24.3,normal,76,95,0.80,MR
18,ID19,A,71,68.6,159.0,27.1,sobrepeso,106,117,0.91,GR
19,ID20,A,63,51.0,150.0,22.7,normal,71,83,0.86,GR
20,ID21,A,60,53.4,150.0,23.7,normal,76,89,0.85,MR
21,ID22,A,69,61.3,154.0,25.8,sobrepeso,89,106,0.84,MR
22,ID23,A,64,53.2,158.0,21.3,normal,73,86,0.85,MR
23,ID24,A,63,54.6,150.0,24.3,normal,80,108,0.74,PR
24,ID25,A,66,56.2,152.0,24.3,normal,84,110,0.76,PR
25,ID26,A,71,60.3,156.0,24.8,normal,82,99,0.83,MR
26,ID27,A,64,54.7,158.0,21.9,normal,76,95,0.80,MR
27,ID28,A,70,60.0,160.0,23.4,normal,81,104,0.78,MR
28,ID29,A,63,51.3,154.0,21.6,normal,76,89,0.85,MR
29,ID30,A,66,50.0,153.0,21.4,normal,76,87,0.87,GR
30,ID31,A,64,49.8,150.0,22.1,normal,72,106,0.68,PR
31,ID32,A,69,55.2,156.0,22.7,normal,81,98,0.83,MR
32,ID33,A,69,58.2,160.0,22.7,normal,78,90,0.87,GR
33,ID34,S,64,51.6,156.5,21.1,normal,76,87,0.87,GR
34,ID35,S,63,62.7,153.0,26.8,sobrepeso,90,103,0.87,GR
35,ID36,S,72,75.6,165.0,27.8,sobrepeso,98,110,0.89,GR
36,ID37,S,73,65.2,154.0,27.5,sobrepeso,96,110,0.87,GR
37,ID38,S,68,61.8,152.0,26.7,sobrepeso,82,93,0.88,GR
38,ID39,S,71,64.3,150.0,28.6,sobrepeso,78,89,0.88,GR
39,ID40,S,72,59.2,153.0,25.3,sobrepeso,73,82,0.89,GR
40,ID41,A,69,63.4,163.0,23.9,normal,93,120,0.78,MR
41,ID42,S,68,66.0,160.0,25.8,sobrepeso,90,117,0.77,PR
42,ID43,S,68,61.7,158.0,24.7,normal,90,116,0.78,MR
43,ID44,S,73,68.2,155.0,28.4,sobrepeso,107,120,0.89,GR
44,ID45,S,79,60.1,160.0,23.5,normal,92,110,0.84,MR

In [2]:
import Funcoes.Conversao as Conv

In [3]:
# Media para a variavel idade
Conv.media(df2['idade'])

67.2

In [4]:
# Mediana para variavel idade
Conv.mediana(df2['idade'])

68

In [5]:
serie = [1,7,8,9,3,2]
n = len(serie)
posicao = (n // 2)
media = np.sum(serie[posicao : posicao + 1]) / 2
n = len(serie)
serie_ordered = np.sort(serie)
inicio = n // 2
fim = inicio + 2
print('Dados Brutos',serie)
print('ROL dos elementos', serie_ordered)
print('Numero de elementos: ',n)
print(media)
#Conv.mediana()

Dados Brutos [1, 7, 8, 9, 3, 2]
ROL dos elementos [1 2 3 7 8 9]
Numero de elementos:  6
4.5

In [6]:
Conv.mediana([1,7,8,9,3,2])

[7 8]

In [8]:
df2['idades'].sort_values().iloc(1,3)

KeyError: 'idades'